_BASE_: configs/bs_kitti_dla34.yaml

DATA:
  BATCH_SIZE: 16
  IMG_HEIGHT: 384
  IMG_WIDTH: 1280

TRAIN:
  MAX_EPOCHS: 128
  LOGGING_ITER: 50
  FIGSAVE_ITER: 500
  LR_MILESTONES: [90, 115]
  WARMUP_ITERS: 2000
  GRAD_CLIP: 30.0

MODEL:
  BS:
    NAME: 'dla_iam'
    NUM_LAYERS: 34
    PRIOR_PROB: 0.1
    DOWN_RATIO: 16
    GROUP_NORM: True
    DEFORMABLE: True
