_BASE_: configs/bs_kitti_default.yaml

DATA:
  BATCH_SIZE: 48
  IMG_HEIGHT: 192
  IMG_WIDTH: 640

TRAIN:
  MAX_EPOCHS: 90
  LOGGING_ITER: 50
  FIGSAVE_ITER: 300
  LR_MILESTONES: [60, 75]
  WARMUP_ITERS: 300
  GRAD_CLIP: 50.0

MODEL:
  BS:
    NAME: 'dla_iam'
    NUM_LAYERS: 34
    PRIOR_PROB: 0.1
    DOWN_RATIO: 8
    GROUP_NORM: True
    DEFORMABLE: True
