_BASE_: configs/bs_kitti_default.yaml

DATA:
  BATCH_SIZE: 64
  IMG_HEIGHT: 192
  IMG_WIDTH: 640

TRAIN:
  MAX_EPOCHS: 60
  LOGGING_ITER: 50
  FIGSAVE_ITER: 300
  LR_MILESTONES: [40, 50]
  WARMUP_ITERS: 300
  GRAD_CLIP: 50.0

MODEL:
  BS:
    NAME: 'sparseinst_iam'
    NUM_LAYERS: 18
    PRIOR_PROB: 0.1
    DOWN_RATIO: 8
