_BASE_: configs/bs_kitti_default.yaml

DATA:
  NAME: 'nusc'
  ROOT_DIR: '@REQUIRED@'
  TRAIN_SPLIT: 'splits/nusc/bs/train_files.txt'
  VAL_SPLIT: 'splits/nusc/bs/val_files.txt'
  TEST_SPLIT: 'splits/nusc/bs/test_files.txt'
  BS_LABEL: '@REQUIRED@'
