_BASE_: 'configs/bsgt_default.yaml'
NUM_WORKERS: 2

DATA:
  NAME: 'DDAD'
  TRAIN_SPLIT: 'splits/ddad/bs/train_files.txt'
  VAL_SPLIT: 'splits/ddad/bs/val_files.txt'
  TEST_SPLIT: 'splits/ddad/bs/val_files.txt'

  BATCH_SIZE: 1
  IMG_HEIGHT: 192
  IMG_WIDTH: 640

  FRAME_IDXS: [
     0,
   -10, -9, -8, -7, -6, -5, -4, -3, -2, -1,
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

OGM:
  SAMPLING_ACCEPT_OFFSET: 0.15
