TARGET_MODE: 'bs_gen'

DATA:
  ROOT_DIR: '@REQUIRED@'
  NO_SHUFFLE: True
  SCALES: [0]

TRAIN:
  MAX_EPOCHS: 1

MODEL:
  DEPTH:
    ENABLED: True
    NUM_LAYERS: 18
    SCALES: [0]
    MIN_DEPTH: 0.1
    MAX_DEPTH: 100
    WEIGHT: '@REQUIRED@'

  POSE:
    ENABLED: True
    NUM_LAYERS: 18
    WEIGHT: '@REQUIRED@'

  BS:
    ENABLED: False

OGM:
  SIZE: 128
  SUBGRIDS: 32
  MEDIAN_SCALE: 16
  THRESHOLD: 0.55
  COUNT_THRESHOLD: 3
  DEPTH_GRAD_THRESHOLD: 0.0005
  HEIGHT_QUANTILE: 0.75
  MIN_PRIOR_PROB: 0.35
  MAX_PRIOR_PROB: 0.65
  UNKNOWN_PRIOR_PROB: 0.50
  POOLING_KERNEL_SIZE: 9
  SAMPLING_ACCEPT_OFFSET: 0.1

  RANSAC_ITERATIONS: 1000

EVAL:
  BS:
    ERROR_THRESHOLD: 0.75
