_BASE_: configs/depth_kitti.yaml
NUM_WORKERS: 2

DATA:
  BATCH_SIZE: 2
  IMG_HEIGHT: 384
  IMG_WIDTH: 1280

TRAIN:
  MAX_EPOCHS: 15
  LOGGING_ITER: 50
  FIGSAVE_ITER: 1000
  LR_MILESTONES: [10]
  EVAL_BATCHES: 200

MODEL:
  DEPTH:
    NUM_LAYERS: 18

  POSE:
    NUM_LAYERS: 18
