name: test

on:
  push:
    branches:
      - "main"
    paths:
      - 'bse/**'
      - 'tests/**'
      - '*.py'

  pull_request:
    branches:
      - "main"
jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          pip install --upgrade pip
          pip3 install \
            torch torchvision torchaudio \
            --extra-index-url https://download.pytorch.org/whl/cu113
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests
